name: Deploy via SSH

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Ubuntu VM
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.HOST }}
          port: 14768
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            set -e
            cd /home/pranav || exit 1
            if [ ! -d "devops-node-app" ]; then
              echo "ğŸ“¦ Cloning repository..."
              git clone https://github.com/PrAnAvViNaYaKjAdHaV/node-devops-app.git
            fi

            echo "ğŸ“‚ Changing into project directory..."
            cd /home/pranav/devops-node-app || { echo "âŒ Failed to enter directory"; exit 1; }

            echo "ğŸ”„ Pulling latest code..."
            git pull origin main

            echo "ğŸ³ Rebuilding Docker container..."
            sudo docker stop node-app || true
            sudo docker rm node-app || true
            sudo docker build -t node-app .
            sudo docker run -d -p 3000:3000 --name node-app node-app

            echo "âœ… Deployment complete!"
